CREATE TABLE IF NOT EXISTS ordencompras(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    usuario TEXT NOT NULL CHECK (usuario <> ''),
    productos INTEGER REFERENCES productos(id),
    precio FLOAT NOT NULL,
    estatus TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS productos(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre TEXT NOT NULL CHECK (nombre <> ''),
    cantidad INT NOT NULL,
    precio FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS usuarios(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre TEXT NOT NULL CHECK (nombre <> ''),
    correo TEXT NOT NULL,
    contrasena TEXT NOT NULL
);
